language:
  - node_js
node_js:
  - node
  - "6.1"
  - "5.11"
addons:
  postgresql: "9.4"
before_install:
  - rvm install 2.3.1
install:
  - npm install -g tape
  - npm install
  - bundle install
before_script:
  - psql -c 'create database OpenUp_test;' -U postgres
script:
  - rspec
