language:
  - node_js
node_js:
  - node
  - "6.1"
  - "5.11"
addons:
  postgresql: "9.4"
before_install:
  - rvm install 2.3.1
install:
  - bundle install
  - cd client
  - npm install
  - cd ..
before_script:
  - rake db:create
  - rake db:migrate
script:
  - cd client
  - npm test
  - cd ..
  - rspec
